# Generated by Django 5.2.8 on 2025-11-10 09:00

from django.db import migrations


def provide_sample_product(apps, schema_editor):
    Product = apps.get_model("shop", "Product")
    sample_product = Product(title='Sample')
    sample_product.save()


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(provide_sample_product),
    ]
